# Generated by Django 5.2.6 on 2025-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=50)),
                ("p_desc", models.TextField(max_length=100)),
                ("p_price", models.FloatField(max_length=50)),
            ],
        ),
    ]
