# Generated by Django 5.2.7 on 2025-10-08 10:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_blogmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="blog_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="blog_title",
                unique=True,
            ),
        ),
    ]
