# Generated by Django 5.2.7 on 2025-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_blogmodel_blog_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("username", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
