# Generated by Django 5.2.7 on 2025-10-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_signupmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="appmodel",
            name="p_image",
            field=models.FileField(default=None, null=True, upload_to="products/"),
        ),
    ]
