# Generated by Django 5.2.7 on 2025-10-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_appmodel_p_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="blog_image",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="blogs/"
            ),
        ),
    ]
